<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\WoowzLib\WoowzLib.Core\WoowzLib.Core.csproj" />
        <ProjectReference Include="..\WoowzLib\WoowzLib.Logger\WoowzLib.Logger.csproj" />
        <ProjectReference Include="..\WoowzLib\WoowzLib.Window\WoowzLib.Window.csproj" />
    </ItemGroup>

</Project>
